version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=8080
      - HOST=0.0.0.0
      - CORS_ORIGIN=http://localhost:*
      - COMMON_RATE_LIMIT_WINDOW_MS=1000
      - COMMON_RATE_LIMIT_MAX_REQUESTS=20
      # Database connection info
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=srv_db
      - DB_SYNC=true
    command: npm run dev

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=srv_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: